name: Build

on:
  push:
    branches:
      - "master"
    tags:
      - 'v*'
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/images/**'
      - 'config.yaml'
      - 'docker-compose.yml'
      - 'Makefile'
      - '**.md'
  pull_request:
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/images/**'
      - 'config.yaml'
      - 'docker-compose.yml'
      - 'Makefile'
      - '**.md'

env:
  GO_VERSION: '1.25'

permissions:
  contents: write
  packages: write

jobs:
  unit:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Run Tests
        run: go test -race ./...

  test:
    name: Integration tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - container_image: "docker.io/crazymax/rtorrent-rutorrent:latest"
            container_name: latest
          - container_image: "docker.io/crazymax/rtorrent-rutorrent:4.3.1-0.9.8_3-0.13.8_2"
            container_name: legacy
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Run Tests
        env:
          RTORRENT_TEST_IMAGE: ${{ matrix.config.container_image }}
        run: |
          echo "Running tests against ${{ matrix.config.container_image }}..."
          go run gotest.tools/gotestsum@latest --junitfile unit-tests-${{ matrix.config.container_name }}.xml --format pkgname -- -tags integration ./...

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "unit-tests-${{ matrix.config.container_name }}.xml"